ALTER TABLE Littera_Notabilior ADD FOREIGN KEY (F_Number, MS_Number) REFERENCES Folio(Number, MS_Number) ON DELETE RESTRICT ON UPDATE RESTRICT ;
ALTER TABLE Enlarged_Capital ADD FOREIGN KEY (F_Number, MS_Number) REFERENCES Folio(Number, MS_Number) ON DELETE RESTRICT ON UPDATE RESTRICT ;
ALTER TABLE Rubric ADD FOREIGN KEY (F_Number, MS_Number) REFERENCES Folio(Number, MS_Number) ON DELETE RESTRICT ON UPDATE RESTRICT ;
ALTER TABLE Intertextual_Space ADD FOREIGN KEY (F_Number, MS_Number) REFERENCES Folio(Number, MS_Number) ON DELETE RESTRICT ON UPDATE RESTRICT ;

ALTER TABLE Training-Enlarged_Capital ADD FOREIGN KEY (F_Number, MS_Number) REFERENCES Folio(Number, MS_Number) ON DELETE RESTRICT ON UPDATE RESTRICT ;
ALTER TABLE Training-Rubric ADD FOREIGN KEY (F_Number, MS_Number) REFERENCES Folio(Number, MS_Number) ON DELETE RESTRICT ON UPDATE RESTRICT ;
ALTER TABLE Training-Littera_Notabilior ADD FOREIGN KEY (F_Number, MS_Number) REFERENCES Folio(Number, MS_Number) ON DELETE RESTRICT ON UPDATE RESTRICT ;
ALTER TABLE Training-Intertextual_Space ADD FOREIGN KEY (F_Number, MS_Number) REFERENCES Folio(Number, MS_Number) ON DELETE RESTRICT ON UPDATE RESTRICT ;
