DELETE FROM Manuscript;
DELETE FROM Date;
DELETE FROM Location;
DELETE FROM Language;
INSERT INTO Manuscript VALUES ('313','Lucius Annaeus Florus, Epitoma de Tito Livio [account of Roman history]. Historia actuum apostolorum [...]',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','313');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','313');
INSERT INTO Language (Language, MS_Number) VALUES (' Middle English','313');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','313');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','313');
INSERT INTO Manuscript VALUES ('470','Kalendar of Norwich Cathedral Priory, Office of the Virgin, Litany, Prayers. Hildebert of Lavardin, De mysterio missae. [...]',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('East of England','Norwich Priory ','470');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','470');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'ex','470');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','470');
INSERT INTO Manuscript VALUES ('252','James of Milan OFM, Stimulus amoris. Planctus beatae Mariae uirginis. Bernard Ayglier OSB, Commentary on Regula Sancti Benedicti. [...]',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','252');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','252');
INSERT INTO Date(Century,Super, MS_Number)VALUES(14,'in','252');
INSERT INTO Manuscript VALUES ('30','Andrew of Saint-Victor OSA, Commentary on the Heptateuch, Commentary on the Minor Prophets. Bede the Venerable, Commentary on Proverbs. [...]',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('East of England','Uncertain (Coggeshall Priory, Essex)','30');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','30');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','30');
INSERT INTO Manuscript VALUES ('505','Spiritual and Medical Tracts. Bulgarus of Bologna, Commentarium in Digestorum ''De diuersis regulis iuris antiqui'' [...]',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('Italy | Germany','','505');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','505');
INSERT INTO Language (Language, MS_Number) VALUES ('German','505');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','505');
INSERT INTO Date(Century,Super, MS_Number)VALUES(14,'','505');
INSERT INTO Manuscript VALUES ('281','Geoffrey of Monmouth, Historia regum Britanniae. Annals (Incarnation-1339) etc. Thomas de la More (attrib.) [...]',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','281');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','281');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','281');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','281');
INSERT INTO Date(Century,Super, MS_Number)VALUES(14,'','281');
INSERT INTO Manuscript VALUES ('439','Robert Grosseteste, Compotus correctorius. Defensor of Ligugé, Liber scintillarum. Isidore of Seville, De ortu et obitu patrum.[...]',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','439');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','439');
INSERT INTO Language (Language, MS_Number) VALUES ('English','439');
INSERT INTO Date(Century,Super, MS_Number)VALUES(15,'','439');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','439');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','439');
INSERT INTO Manuscript VALUES ('339','Richard of Devizes OSB (attrib.), Annales Wintonienses, Chronicon de tempore regis Ricardi. Peter of Ickham OSB, [...] ',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Lilleshull Abbey, Shropshire ','339');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','339');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','339');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'in','339');
INSERT INTO Date(Century,Super, MS_Number)VALUES(14,'','339');
INSERT INTO Manuscript VALUES ('62','Proverbs, Ecclesiastes, and Song of Songs with Gloss. Vita of and works by Bernard of Clairvaux OCist. Bede the Venerable, [...]',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','Cathedral Priory of St. Andrews, Rochester, Kent','62');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','62');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','62');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','62');
INSERT INTO Manuscript VALUES ('66A','Jacques de Vitry, Historia orientalis. Willelmus de Rubruk OFM, Itinerarium ad partes orientales. pseudo-John of Damascus, [...]',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('East of England','Bury St. Edmonds Abbey','66A');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','66A');
INSERT INTO Language (Language, MS_Number) VALUES (' Anglo-Norman','66A');
INSERT INTO Language (Language, MS_Number) VALUES (' English','66A');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','66A');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','66A');
INSERT INTO Date(Century,Super, MS_Number)VALUES(14,'','66A');
INSERT INTO Manuscript VALUES ('356','Richard of Wetheringsett, Hugh of Saint-Victor OSA, Alanus ab Insula (Alain de Lille), Petrus Comestor, [...]',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','356');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','356');
INSERT INTO Date(Century,Super, MS_Number)VALUES(9,'','356');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','356');
INSERT INTO Date(Century,Super, MS_Number)VALUES(14,'','356');
INSERT INTO Manuscript VALUES ('139','Simeon of Durham OSB, Historia regum. Richard of Hexham OSA, De gestis regis Stephani et de bello standardii. [...]',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('North East England','Religious houses of Hexham, Fountains, Sawley, and Durham (most likely Hexham)','139');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','139');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','139');
INSERT INTO Manuscript VALUES ('337','Defensor of Ligugé, Liber scintillarum. Richard of Wetheringsett, Summa Qui bene praesunt. pseudo-Robert Grosseteste, [...]',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','337');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','337');
INSERT INTO Language (Language, MS_Number) VALUES ('Middle English','337');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','337');
INSERT INTO Manuscript VALUES ('452','Eadmer of Canterbury OSB [Order of St. Benedict], Historia nouorum in Anglia [...]',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','Christ Church, Canterbury','452');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','452');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','452');
INSERT INTO Manuscript VALUES ('267','Frechulf of Lisieux, Chronica. Peter Damian OSB, De nouissimis et Antichristo. John Thwing of Bridlington OSA, [...]',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','St. Augustine''s Abbey, Canterbury ','267');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','267');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','267');
INSERT INTO Manuscript VALUES ('134','Berengaudus, Expositio super septem uisiones libri Apocalypsis ["Exposition on the seven visions of the Apocalypse book"]',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','134');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','134');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','134');
INSERT INTO Manuscript VALUES ('12','Alfred the Great''s Old English Translation of Gregory the Great, De cura pastorali ["On the care of shepherds/pastors"]',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','12');
INSERT INTO Language (Language, MS_Number) VALUES ('Old English','12');
INSERT INTO Language (Language, MS_Number) VALUES (' Latin','12');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','12');
INSERT INTO Manuscript VALUES ('273','Theological Works by Gandulf of Bologna, Bernard of Clairvaux and Remigius of Auxerre. Arnulf of Lisieux, Epistola',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','273');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','273');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','273');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','273');
INSERT INTO Manuscript VALUES ('292','Geoffrey of Monmouth, Historia regum Britanniae. pseudo-Turpinus, Historia Caroli magni et Rolandi. Charters, etc.',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','292');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','292');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','292');
INSERT INTO Date(Century,Super, MS_Number)VALUES(14,'','292');
INSERT INTO Manuscript VALUES ('451','Hildebert of Lavardin, Epistolae. Apollonius of Tyre. Miscellaneous Theological Tracts. Sermons on the Virgin Mary',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','451');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','451');
INSERT INTO Language (Language, MS_Number) VALUES ('Anglo-Norman','451');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'ex','451');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'in','451');
INSERT INTO Manuscript VALUES ('315',' Theological (Exegetical) Works by Richard of Saint-Victor OSA, Andrew of Saint-Victor OSA and Bede the Venerable',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','P: Franciscan convent, Oxford','315');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','315');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','315');
INSERT INTO Manuscript VALUES ('319','Petrus Comestor, Historia scholastica (excerpts). Honorius Augustodunensis, Gemma animae siue De diuinis officiis',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('East of England','Uncertain (St. Albans)','319');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','319');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','319');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','319');
INSERT INTO Manuscript VALUES ('425','Gerald of Wales, Vita Sancti Remigii episcopi, Vita Sancti Hugonis. Peter of Blois, archdeacon of Bath, Epistolae',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','425');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','425');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'in','425');
INSERT INTO Date(Century,Super, MS_Number)VALUES(15,'','425');
INSERT INTO Manuscript VALUES ('461','Exactis regibus. Peter Lombard, Sententiarum abbreuiationes. pseudo-Hugh of Saint Victor OSA, Speculum ecclesiae',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','461');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','461');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'in','461');
INSERT INTO Manuscript VALUES ('222','Richard of Saint-Victor OSA (attrib.), Tractatus de conceptione beatae Mariae, Tractatus de conceptione Christi',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','Christ Church, Canterbury ','222');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','222');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','222');
INSERT INTO Manuscript VALUES ('228','Claudianus Claudius, Claudianus maior. De raptu Proserpinae. Bernardus Silvestris, Cosmographia (Megacosmos)',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','228');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','228');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','228');
INSERT INTO Manuscript VALUES ('200','Baldwin of Ford OCist [Order of the Cistercians], De sacramento altaris ["On the Sacrament of the Altar"]',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','Christ Church, Canterbury','200');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','200');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'ex','200');
INSERT INTO Manuscript VALUES ('469','Basil of Caesarea, Admonitio ad filium spiritualem. Isidore of Seville, Etymologiae (extract). Chronicles',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','469');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','469');
INSERT INTO Language (Language, MS_Number) VALUES ('Anglo-Norman','469');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'ex','469');
INSERT INTO Manuscript VALUES ('94','Collectio decem partium ["A collecting together of ten parts"] (expansion of Ivo of Chartres, Panormia)',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','Christ Church, Canterbury','94');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','94');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','94');
INSERT INTO Manuscript VALUES ('71','Macrobius, Saturnalia, Commentary on Cicero''s Somnium Scipionis. Apuleius, De Platone, De deo Socratis',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('East of England','Uncertain (St. Alban''s Abbey)','71');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','71');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','71');
INSERT INTO Manuscript VALUES ('309','Theological Material in Three Booklets by Richard of Saint-Victor OSA, Petrus Alfonsi and Augustine',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('Yorkshire and the Humber','P: St. Mary''s Abbey, York','309');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','309');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','309');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','309');
INSERT INTO Manuscript VALUES ('11','Hrabanus Maurus, De uniuerso seu De rerum naturis ["On the universe, or On the things of nature"]',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain ','11');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','11');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','11');
INSERT INTO Manuscript VALUES ('321','Petrus Iohannis Olivi OFM, Commentary on Matthew, Quaestiones. Dialogue in Old English (fragment)',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('East of England','Uncertain (Abbey of Ramsey)','321');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','321');
INSERT INTO Language (Language, MS_Number) VALUES ('Old English','321');
INSERT INTO Date(Century,Super, MS_Number)VALUES(14,'','321');
INSERT INTO Manuscript VALUES ('27',' Zacharias of Besançon OPrem [Order of Prémontré], De concordia euangelistarum [gospel harmony]',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('East of England','Uncertain (Leiston Abbey, Suffolk)','27');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','27');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','27');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','27');
INSERT INTO Manuscript VALUES ('367','Miscellaneous Compilation including Old English Material and Historical and Philosophical Works',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','COMPLICATED','367');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','367');
INSERT INTO Language (Language, MS_Number) VALUES ('Old English','367');
INSERT INTO Date(Century,Super, MS_Number)VALUES(15,'','367');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','367');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','367');
INSERT INTO Date(Century,Super, MS_Number)VALUES(14,'','367');
INSERT INTO Manuscript VALUES ('51','Eusebius of Caesarea, Chronici canones, transl. by Jerome. Sigebert of Gembloux OSB, Chronica',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','51');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','51');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'ex','51');
INSERT INTO Manuscript VALUES ('400','Gerald of Wales, Topographia Hiberniae, Verses, etc. Verses from Canterbury Cathedral Windows',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','400');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','400');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','400');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','400');
INSERT INTO Date(Century,Super, MS_Number)VALUES(15,'','400');
INSERT INTO Date(Century,Super, MS_Number)VALUES(14,'','400');
INSERT INTO Manuscript VALUES ('271','Gregory IX, Decretales (Liber extra). Boniface VIII, Liber Sextus. Constitutiones Anglicanae',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','271');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','271');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','271');
INSERT INTO Date(Century,Super, MS_Number)VALUES(14,'in','271');
INSERT INTO Manuscript VALUES ('322','Werferth of Worcester''s Old English Translation of Gregory the Great''s Dialogi ["Dialogues"]',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('West Midlands','Uncertain (Worcester)','322');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','322');
INSERT INTO Language (Language, MS_Number) VALUES ('Old English','322');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','322');
INSERT INTO Manuscript VALUES ('50','Wace, Roman de Brut. Roman de Guy de Warewic. and other works (in French and Anglo-Norman) ',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','50');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','50');
INSERT INTO Language (Language, MS_Number) VALUES (' Anglo-Norman','50');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'1','50');
INSERT INTO Manuscript VALUES ('397','Peter the Chanter, Distinctiones Abel. Petrus Riga, Aurora. Miscellaneous Theological Texts',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','397');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','397');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','397');
INSERT INTO Date(Century,Super, MS_Number)VALUES(16
,'','397');
INSERT INTO Manuscript VALUES ('149','Hegesippus (attrib.), Historia Iosephi de bello iudaico et excidio urbis Hierosolymitanae',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('North East England','Uncertain (Hexham Priory)','149');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','149');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','149');
INSERT INTO Manuscript VALUES ('253','Augustine, Confessiones. Ferrandus, Epistola ad Reginum comitem. Hymn for Augustine, etc.',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','Uncertain (Canterbury or Rochester)','253');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','253');
INSERT INTO Language (Language, MS_Number) VALUES (' Middle English','253');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','253');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','253');
INSERT INTO Manuscript VALUES ('475','Zacharias of Besan on OPrem, De concordia euangelistarum ["On the Harmony of the Gospels"',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','475');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','475');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'in','475');
INSERT INTO Manuscript VALUES ('380','Robert of Cricklade OSA [Order of St. Augustine], Speculum fidei ["The Mirror of Faith"]',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South West England','Uncertain (Malmesbury)','380');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','380');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','380');
INSERT INTO Manuscript VALUES ('277','Adam of Barking, Carmen de serie sex aetatum ["Song concerning a series of six years"]',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','277');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','277');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','277');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','277');
INSERT INTO Manuscript VALUES ('316','Works by Hugh of Saint-Victor OSA, Augustine, Alexander of Canterbury OSB, and others',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('London','P: Dominican convent, London','316');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','316');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'in','316');
INSERT INTO Manuscript VALUES ('330','Martianus Capella, De nuptiis Philologiae et Mercurii; Glossary on Martianus Capella',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','330');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','330');
INSERT INTO Date(Century,Super, MS_Number)VALUES(10,'','330');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','330');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','330');
INSERT INTO Manuscript VALUES ('41','Old English translation of Bede''s Historia Ecclesiastica ["Ecclesiastical history"]',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','41');
INSERT INTO Language (Language, MS_Number) VALUES ('Old English','41');
INSERT INTO Language (Language, MS_Number) VALUES (' Latin','41');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','41');
INSERT INTO Manuscript VALUES ('10','Gratian, Decretum (Concordia discordantium canonum) [12th c. canon law collection]',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','10');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','10');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','10');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','10');
INSERT INTO Manuscript VALUES ('107','Seneca, Tragedies. François de Meyronnes OFM, De indulgentiis. Miscellaneous Texts',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','107');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','107');
INSERT INTO Date(Century,Super, MS_Number)VALUES(15,'ex','107');
INSERT INTO Date(Century,Super, MS_Number)VALUES(16,'in','107');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','107');
INSERT INTO Manuscript VALUES ('275','Legends of Saints. Prayers. Mandeville''s Travels. Odoricus of Pordenone, Itinerary',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','P: Given to the College by Thomas Markaunt (d. 1439).','275');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','275');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','275');
INSERT INTO Date(Century,Super, MS_Number)VALUES(15,'','275');
INSERT INTO Manuscript VALUES ('308','Osbert of Clare OSB, Vita Sancti Ethelberti. Honorius Augustodunensis, Elucidarius',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain ','308');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','308');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','308');
INSERT INTO Manuscript VALUES ('385','Tractatus monachi peccatoris. William of Conches, Dragmaticon. Miscellaneous Works',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','COMPLICATED','385');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','385');
INSERT INTO Language (Language, MS_Number) VALUES ('Middle English','385');
INSERT INTO Language (Language, MS_Number) VALUES ('Anglo-Norman','385');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','385');
INSERT INTO Date(Century,Super, MS_Number)VALUES(14,'','385');
INSERT INTO Manuscript VALUES ('22','Isidore of Seville, Etymologiae ["Etymoligies"], Synonyma ["Synonyms"]. Bestiary',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','22');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','22');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','22');
INSERT INTO Date(Century,Super, MS_Number)VALUES(14,'','22');
INSERT INTO Manuscript VALUES ('274','Ambrose or pseudo-Ambrose (i.e. by or attributed to Ambrose), Works on Virginity',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','Christ Church, Canterbury ','274');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','274');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','274');
INSERT INTO Manuscript VALUES ('481','Miscellaneous Moral, Penitential and Theological Treatises, Exempla and Verses',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','481');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','481');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'in','481');
INSERT INTO Manuscript VALUES ('131','Cassiodorus Senator, Expositio psalmorum 1-50 ["Explanation of psalms 1-50"]',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','131');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','131');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','131');
INSERT INTO Manuscript VALUES ('406','Seneca, Tragedies. Iohannes de Alta Villa, Architrenius. Miscellaneous Texts',3);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','406');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','406');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','406');
INSERT INTO Manuscript VALUES ('111','The Bath Cartulary and related items. Antiquarian Transcripts of Charters',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','111');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','111');
INSERT INTO Language (Language, MS_Number) VALUES ('Old English','111');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','111');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','111');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','111');
INSERT INTO Date(Century,Super, MS_Number)VALUES(14,'','111');
INSERT INTO Date(Century,Super, MS_Number)VALUES(15,'','111');
INSERT INTO Date(Century,Super, MS_Number)VALUES(16,'','111');
INSERT INTO Manuscript VALUES ('295','Thomas Becket, Epistolae (Alan of Tewkesbury''s Collection, Recension III)',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','Christ Church, Canterbury','295');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','295');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'in','295');
INSERT INTO Manuscript VALUES ('204','Stephen Langton, Commentaries on Isaiah, Kings, Chronicles and Maccabees',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','204');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','204');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','204');
INSERT INTO Manuscript VALUES ('320','Sermons by Geoffrey Babio du Louroux and others. Anglo-Saxon Penitential',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','St. Augustine''s, Canterbury ','320');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','320');
INSERT INTO Language (Language, MS_Number) VALUES ('Old English','320');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','320');
INSERT INTO Manuscript VALUES ('364','Medical Tracts. Iohannitius, Hippocrates, Theophilius, Philaretus, Galen',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','P: William de Elham (c. 1300) to Canterbury','364');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','364');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','364');
INSERT INTO Manuscript VALUES ('66',' Imago mundi. Pliny. Historia Anglorum. Miscellaneous Theological Texts',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('North West England','Sawley Abbey','66');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','66');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','66');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','66');
INSERT INTO Date(Century,Super, MS_Number)VALUES(14,'','66');
INSERT INTO Manuscript VALUES ('376','Roger Taverner, De fame ["Of the Means to Prevent Famine in this Land"]',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','376');
INSERT INTO Language (Language, MS_Number) VALUES ('English','376');
INSERT INTO Date(Century,Super, MS_Number)VALUES(16,'','376');
INSERT INTO Manuscript VALUES ('459','Miscellaneous Moral, Penitential and Theological Treatises and Sermons',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('East of England','Uncertain (Peterborough)','459');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','459');
INSERT INTO Language (Language, MS_Number) VALUES ('English','459');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','459');
INSERT INTO Manuscript VALUES ('92','John of Worcester OSB (''Florence of Worcester''), Chronica chronicarum',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','Abingdon Abbey','92');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','92');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'ex','92');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','92');
INSERT INTO Date(Century,Super, MS_Number)VALUES(14,'','92');
INSERT INTO Manuscript VALUES ('300','Pictor in carmine ["The Painter in verse" => a treatise for painters]',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('West Midlands','Herefordshire','300');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','300');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','300');
INSERT INTO Manuscript VALUES ('55','Stephen Langton, Commentaries on Selected Books of the Old Testament',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','55');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','55');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','55');
INSERT INTO Manuscript VALUES ('89','Stephen Langton, Commentaries on Selected Books of the Old Testament',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('East of England','St. Mary''s, Coggeshall ','89');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','89');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','89');
INSERT INTO Manuscript VALUES ('186','William de Montibus, Distinctiones theologicae, Versarius, Numerale',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','186');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','186');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','186');
INSERT INTO Manuscript VALUES ('405','Charters, Letters, Bulls, Liturgical Texts, Anglo-Norman Texts etc.',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain ','405');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','405');
INSERT INTO Language (Language, MS_Number) VALUES ('Middle English','405');
INSERT INTO Language (Language, MS_Number) VALUES (' Anglo-Norman','405');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','405');
INSERT INTO Date(Century,Super, MS_Number)VALUES(14,'in','405');
INSERT INTO Manuscript VALUES ('288',' Alan of Tewkesbury OSB, Epistolae. Apocryphal Gospels. Prophecies',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','P: Christ Church, Canterbury ','288');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','288');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','288');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','288');
INSERT INTO Manuscript VALUES ('441','Miscellaneous Theological, Penitential, Moral and Didactic Tracts',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','441');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','441');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','441');
INSERT INTO Manuscript VALUES ('130','Collectio Lanfranci [collection of ''pseudo-Isidorian decretals'']',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','Canterbury','130');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','130');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','130');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','130');
INSERT INTO Manuscript VALUES ('140','The Bath Old English Gospels [Gospels in West-Saxon Old English]',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South West England','Bath Abbey','140');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','140');
INSERT INTO Language (Language, MS_Number) VALUES ('Old English','140');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','140');
INSERT INTO Manuscript VALUES ('184','Eusebius of Caesarea, Historia ecclesiastica, transl. by Rufinus',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','Christ Church, Canterbury ','184');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','184');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','184');
INSERT INTO Manuscript VALUES ('187','Eusebius of Caesarea, Historia ecclesiastica, transl. by Rufinus',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','P: Priory of Christ Church, Canterbury ','187');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','187');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','187');
INSERT INTO Manuscript VALUES ('178','Old English Homilies. Benedictine Rule in Latin and Old English',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('West Midlands','Worcester Priory ','178');
INSERT INTO Language (Language, MS_Number) VALUES ('Old English','178');
INSERT INTO Language (Language, MS_Number) VALUES (' Latin','178');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','178');
INSERT INTO Manuscript VALUES ('361','Gregory the Great, De cura pastorali ["On the care of pastors"]',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South West England','P: Malmsebury Abbey','361');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','361');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','361');
INSERT INTO Manuscript VALUES ('404','Miscellany of Prophecy Texts compiled by Henry of Kirkstead OSB',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('East of England','Bury St. Edmonds','404');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','404');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','404');
INSERT INTO Date(Century,Super, MS_Number)VALUES(14,'','404');
INSERT INTO Manuscript VALUES ('52','Peter Lombard, Gloss on the Pauline Epistles (Magna glosatura)',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','52');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','52');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','52');
INSERT INTO Manuscript VALUES ('83','Petrus Riga, Aurora. Peter of Poitiers, Genealogia historiarum',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','83');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','83');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','83');
INSERT INTO Manuscript VALUES ('462','Recapitulatio historiarum bibliae. Lanfranc OSB, Consuetudines',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','Dover Priory ','462');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','462');
INSERT INTO Language (Language, MS_Number) VALUES ('Anglo-Norman','462');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','462');
INSERT INTO Manuscript VALUES ('17',' Augustine, Tractatus in euangelium Iohannis, and other works',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('East of England','Uncertain (Norwich)','17');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','17');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','17');
INSERT INTO Manuscript VALUES ('266','Peter of Blois, archdeacon of Bath, Epistolae and other works',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('London','London Carmelites','266');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','266');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'in','266');
INSERT INTO Manuscript VALUES ('312','Goscelin of Saint-Bertin, Works on St Augustine of Canterbury',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','P: Bachon then Parker','312');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','312');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','312');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','312');
INSERT INTO Manuscript VALUES ('16I','Matthew Paris OSB, Chronica maiora II ["Major Chronicle II"]',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','16I');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','16I');
INSERT INTO Language (Language, MS_Number) VALUES (' Anglo-Norman','16I');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','16I');
INSERT INTO Manuscript VALUES ('16II','Matthew Paris OSB, Chronica maiora II ["Major Chronicle II"]',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','16II');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','16II');
INSERT INTO Language (Language, MS_Number) VALUES (' Anglo-Norman','16II');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','16II');
INSERT INTO Manuscript VALUES ('212','Sermons attributed to Gibuinus of Troyes and Petrus Comestor',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain ','212');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','212');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'ex','212');
INSERT INTO Manuscript VALUES ('390','Gerald of Wales, De uita Galfridi archiepiscopi Eboracensis',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','390');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','390');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'ex','390');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'in','390');
INSERT INTO Manuscript VALUES ('26','Matthew Paris OSB, Chronica maiora I ["Major Chronicle I"]',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('East of England','St. Albans','26');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','26');
INSERT INTO Language (Language, MS_Number) VALUES (' Anglo-Norman','26');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','26');
INSERT INTO Manuscript VALUES ('29','Petrus Comestor, Historia scholastica [Scholastic History]',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain ','29');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','29');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'in','29');
INSERT INTO Manuscript VALUES ('289',' Doctrinal works by Augustine, Ivo of Chartres, and others',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','289');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','289');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','289');
INSERT INTO Manuscript VALUES ('310','Hugh of Saint-Victor OSA, De sacramentis christianae fidei',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','310');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','310');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','310');
INSERT INTO Manuscript VALUES ('457','Alexander of Canterbury OSB, Liber ex dictis beati Anselmi',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','Uncertain (Canterbury)','457');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','457');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'in','457');
INSERT INTO Manuscript VALUES ('65','Patristic Homily Collection, compiled by Paul the Deacon',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','65');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','65');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','65');
INSERT INTO Manuscript VALUES ('196','Old English Martyrology. Old English Vindicta saluatoris',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South West England','Exeter','196');
INSERT INTO Language (Language, MS_Number) VALUES ('Old English','196');
INSERT INTO Date(Century,Super, MS_Number)VALUES(10,'in','196');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'in','196');
INSERT INTO Manuscript VALUES ('299',' Letters of Ivo of Chartres and Anselm of Canterbury OSB',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('London','P:  John Tille OP (d. 1410) to the Dominicans of London','299');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','299');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','299');
INSERT INTO Manuscript VALUES ('188','Old English Homilies, mostly from Ælfric''s First Series',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','Uncertain (Eynsham)','188');
INSERT INTO Language (Language, MS_Number) VALUES ('Old English','188');
INSERT INTO Language (Language, MS_Number) VALUES (' Latin','188');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','188');
INSERT INTO Manuscript VALUES ('201','Old English Religious and Legal Texts, many by Wulfstan',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','COMPLICATED','201');
INSERT INTO Language (Language, MS_Number) VALUES ('Old English','201');
INSERT INTO Language (Language, MS_Number) VALUES (' Latin','201');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','201');
INSERT INTO Manuscript VALUES ('202','Symmachus, Epistolae. Glossed Proverbs and Ecclesiastes',3);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','202');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','202');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'ex','202');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','202');
INSERT INTO Manuscript VALUES ('164','Ranulf Higden OSB, Polychronicon. Biblia pauperum etc.',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','164');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','164');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','164');
INSERT INTO Date(Century,Super, MS_Number)VALUES(14,'','164');
INSERT INTO Date(Century,Super, MS_Number)VALUES(15,'','164');
INSERT INTO Manuscript VALUES ('226','Stephen Langton, De poenitentia sub persona Magdalenae',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','Christ Church, Canterbury','226');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','226');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','226');
INSERT INTO Manuscript VALUES ('265','Wulfstan''s Handbook and other ecclesiastical extracts',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('West Midlands','Worcester','265');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','265');
INSERT INTO Language (Language, MS_Number) VALUES ('Old English','265');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','265');
INSERT INTO Manuscript VALUES ('54','Odo of Canterbury OSB, Commentary on Genesis-Numbers',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('East of England','Uncertain (St. Mary''s, Coggeshall)','54');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','54');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'ex','54');
INSERT INTO Manuscript VALUES ('150','William Pore OCist, Nouale. Peter the Chanter et al.',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('East of England','Uncertan (Swineshead, Lincolnshire)','150');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','150');
INSERT INTO Language (Language, MS_Number) VALUES ('Anglo-Norman','150');
INSERT INTO Language (Language, MS_Number) VALUES ('Middle English','150');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','150');
INSERT INTO Manuscript VALUES ('191','Enlarged Rule of Chrodegang in Latin and Old English',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','191');
INSERT INTO Language (Language, MS_Number) VALUES ('Old English','191');
INSERT INTO Language (Language, MS_Number) VALUES (' Latin','191');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'in','191');
INSERT INTO Manuscript VALUES ('375','Metrical Lives of St Katherine and St Ælfheah, Hymns',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('East of England','St. Albans','375');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','375');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','375');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','375');
INSERT INTO Manuscript VALUES ('31','Stephen Langton, Commentaries on the Minor Prophets',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('East of England','Coggeshall ','31');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','31');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','31');
INSERT INTO Manuscript VALUES ('135','Anselm of Canterbury OSB, Letters and related works',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('East of England','Bury St. Edmonds','135');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','135');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','135');
INSERT INTO Manuscript VALUES ('160','Bede the Venerable, Commentary on Catholic Epistles',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('East of England','Peterborough Abbey','160');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','160');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','160');
INSERT INTO Manuscript VALUES ('236','Marcus Valerius Martialis, Epigrammata ["Epigrams"]',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','236');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','236');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'in','236');
INSERT INTO Manuscript VALUES ('262','William of Newburgh OSA, Historia rerum Anglicarum',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','262');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','262');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'in','262');
INSERT INTO Manuscript VALUES ('28','Origen, Homilies on Numbers (transl. by Rufinus)',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','Abingdon','28');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','28');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','28');
INSERT INTO Manuscript VALUES ('345','Hilary of Poitiers, De Trinitate and other works',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','Christ Church, Canterbury','345');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','345');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','345');
INSERT INTO Manuscript VALUES ('328','Lives of Saints Dunstan, Odo, Maiolus and Odilo',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','Uncertain (Christ Church, Canterbury) P: St Swithun''s Priory, Winchester','328');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','328');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','328');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'in','328');
INSERT INTO Manuscript VALUES ('424','Astronomical Tracts. Liber de Joseph et Aseneth',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','424');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','424');
INSERT INTO Language (Language, MS_Number) VALUES ('English','424');
INSERT INTO Date(Century,Super, MS_Number)VALUES(14,'','424');
INSERT INTO Date(Century,Super, MS_Number)VALUES(15,'','424');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','424');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','424');
INSERT INTO Manuscript VALUES ('58','Stephen Langton, Commentary on Ecclesiasticus',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','58');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','58');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'in','58');
INSERT INTO Manuscript VALUES ('332','Miscellany largely concerning the Virgin Mary',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','Cathedral priory at Rochester','332');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','332');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','332');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','332');
INSERT INTO Manuscript VALUES ('366','Peter of Blois, archdeacon of Bath, Epistolae',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','Dover Priory','366');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','366');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','366');
INSERT INTO Manuscript VALUES ('46','John of Salisbury, Policraticus, Metalogicon',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','Christ Church, Canterbury ','46');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','46');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','46');
INSERT INTO Date(Century,Super, MS_Number)VALUES(15,'','46');
INSERT INTO Manuscript VALUES ('263','Honorius Augustodunensis, Speculum ecclesiae',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','263');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','263');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','263');
INSERT INTO Manuscript VALUES ('317','Sermons. John Waldeby OESA, Homilies. Tables',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','317');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','317');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'in','317');
INSERT INTO Date(Century,Super, MS_Number)VALUES(15,'','317');
INSERT INTO Manuscript VALUES ('449','Ælfric OSB, Old English Grammar and Glossary',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','449');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','449');
INSERT INTO Language (Language, MS_Number) VALUES ('Old English','449');
INSERT INTO Date(Century,Super, MS_Number)VALUES(16,'','449');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','449');
INSERT INTO Manuscript VALUES ('455','Thomas of Chobham, Summa de arte praedicandi',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','455');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','455');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','455');
INSERT INTO Manuscript VALUES ('23','Anglo-Saxon Illustrated Prudentius. Orosius',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South West England','Uncertain (Malmesbury)','23');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','23');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','23');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','23');
INSERT INTO Manuscript VALUES ('87','Ralph of Flaix OSB, Commentary on Leviticus',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','87');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','87');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','87');
INSERT INTO Manuscript VALUES ('419','Old English Homilies by Wulfstan and others',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Unclear ','419');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','419');
INSERT INTO Language (Language, MS_Number) VALUES ('Old English','419');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','419');
INSERT INTO Manuscript VALUES ('438','Gervase of Canterbury OSB, Gesta regum etc.',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','438');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','438');
INSERT INTO Language (Language, MS_Number) VALUES ('Middle English','438');
INSERT INTO Language (Language, MS_Number) VALUES (' Anglo-Norman','438');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','438');
INSERT INTO Date(Century,Super, MS_Number)VALUES(14,'','438');
INSERT INTO Date(Century,Super, MS_Number)VALUES(15,'','438');
INSERT INTO Manuscript VALUES ('199','Ieuan ap Sulien''s Augustine on the Trinity',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('Wales','St. David''s','199');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','199');
INSERT INTO Language (Language, MS_Number) VALUES (' Welsh','199');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','199');
INSERT INTO Manuscript VALUES ('219','Gesta Alexandri ["The Deeds of Alexander"]',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('East of England','St. Albans','219');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','219');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'ex','219');
INSERT INTO Manuscript VALUES ('67','Gilbert de la Porrée, Gloss on the Psalms',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','67');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','67');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','67');
INSERT INTO Manuscript VALUES ('229','Nonius Marcellus, De compendiosa doctrina',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','229');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','229');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','229');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','229');
INSERT INTO Manuscript VALUES ('291','Computistical Material by Bede and others',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','St. Augustine''s, Canterbury ','291');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','291');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','291');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','291');
INSERT INTO Manuscript VALUES ('294','Hugh of Saint-Victor OSA, Various Works',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','P: Richard Mabot ','294');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','294');
INSERT INTO Language (Language, MS_Number) VALUES ('Middle English','294');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','294');
INSERT INTO Manuscript VALUES ('402','Ancrene Wisse ["Guide for Anchoresses"]',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','402');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','402');
INSERT INTO Language (Language, MS_Number) VALUES ('Middle English','402');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','402');
INSERT INTO Manuscript VALUES ('86','Hrabanus Maurus, Commentary on Matthew',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('Yorkshire and the Humber','Rievaulx Abbey','86');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','86');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','86');
INSERT INTO Manuscript VALUES ('198','Old English Homilies, mostly by Ælfric',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('West Midlands','Worcester','198');
INSERT INTO Language (Language, MS_Number) VALUES ('Old English','198');
INSERT INTO Language (Language, MS_Number) VALUES (' Latin','198');
INSERT INTO Date(Century,Super, MS_Number)VALUES(10,'','198');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','198');
INSERT INTO Manuscript VALUES ('280','Henry of Huntingdon, Historia Anglorum',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','Uncertain (St. Augustine''s, Canterbury) ','280');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','280');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','280');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','280');
INSERT INTO Manuscript VALUES ('302','Old English Homilies, mostly by Ælfric',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','302');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','302');
INSERT INTO Language (Language, MS_Number) VALUES ('Old English','302');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'ex','302');
INSERT INTO Manuscript VALUES ('327','William de Mauli (attrib.), Abjiciamus',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','327');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','327');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'ex','327');
INSERT INTO Manuscript VALUES ('480','Greek Psalter with Canticles and Hymns',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','480');
INSERT INTO Language (Language, MS_Number) VALUES ('Greek','480');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','480');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','480');
INSERT INTO Manuscript VALUES ('47','Peter the Chanter, Distinctiones Abel',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain ','47');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','47');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','47');
INSERT INTO Manuscript VALUES ('136','Treatises on Confession and Preaching',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','136');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','136');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','136');
INSERT INTO Manuscript VALUES ('290','Ado of Vienne, Chronica ["Chronicle"]',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','Uncertain (Christ Church, Canterbury)','290');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','290');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','290');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','290');
INSERT INTO Manuscript VALUES ('270','Missal of St Augustine''s, Canterbury',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','St. Augustine''s , Canterbury','270');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','270');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','270');
INSERT INTO Manuscript VALUES ('276','Histories of the Romans and Normans',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','St. Augustine''s Abbey, Canterbury','276');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','276');
INSERT INTO Language (Language, MS_Number) VALUES ('Greek','276');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','276');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','276');
INSERT INTO Manuscript VALUES ('416','Amalarius of Metz, Liber officialis',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('East of England','Ely Pirory','416');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','416');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','416');
INSERT INTO Manuscript VALUES ('75','Glossed Psalter (Glossa ordinaria)',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','75');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','75');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'in','75');
INSERT INTO Manuscript VALUES ('269','Anselm of Lucca, Collectio canonum',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('East Midlands','Pipewell Abbey, Northamptonshire','269');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','269');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','269');
INSERT INTO Manuscript VALUES ('371','Eadmer of Canterbury OSB, Opuscula',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','Christ Church, Canterbury (MS of Eadmer of Canterbury)','371');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','371');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','371');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','371');
INSERT INTO Manuscript VALUES ('214','Boethius, Philosophiae consolatio',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','Uncertain (Canterbury)','214');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','214');
INSERT INTO Language (Language, MS_Number) VALUES ('Greek','214');
INSERT INTO Language (Language, MS_Number) VALUES ('Old English','214');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','214');
INSERT INTO Manuscript VALUES ('230','Publius Papinius Statius, Thebais',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','230');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','230');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','230');
INSERT INTO Manuscript VALUES ('33','Glossed Gospels of Mark and John',3);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','33');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','33');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','33');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','33');
INSERT INTO Manuscript VALUES ('373','Ekkehard of Aura OSB, Chronicle',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Germany','373');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','373');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','373');
INSERT INTO Manuscript VALUES ('433','Cluniac Chronicle. Miscellanea',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('West Midlands','Uncertain (St Milburga at Much Wenlock, Shropshire)','433');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','433');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','433');
INSERT INTO Date(Century,Super, MS_Number)VALUES(14,'','433');
INSERT INTO Manuscript VALUES ('163','Pontifical (Romano-Germanic)',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain (Worcester or Winchester)','163');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','163');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','163');
INSERT INTO Manuscript VALUES ('318','Lives of Saints and Romances',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','318');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','318');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','318');
INSERT INTO Manuscript VALUES ('9','The Cotton-Corpus Legendary',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('West Midlands','Uncertain (Worcester Priory)','9');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','9');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','9');
INSERT INTO Manuscript VALUES ('511','Medical Tracts and Receipts',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain (England)','511');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','511');
INSERT INTO Language (Language, MS_Number) VALUES ('Anglo-Norman','511');
INSERT INTO Language (Language, MS_Number) VALUES ('English','511');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'ex','511');
INSERT INTO Manuscript VALUES ('4','The Dover Bible, Volume II',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','Christ Church, Canterbury ','4');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','4');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','4');
INSERT INTO Date(Century,Super, MS_Number)VALUES( 15,'','4');
INSERT INTO Manuscript VALUES ('3','The Dover Bible, Volume I',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','St. Martin''s Priory, Dover','3');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','3');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','3');
INSERT INTO Manuscript VALUES ('468','Psalter (Latin and Greek)',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','468');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','468');
INSERT INTO Language (Language, MS_Number) VALUES ('Greek','468');
INSERT INTO Language (Language, MS_Number) VALUES ('Anglo-Norman','468');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'ex','468');
INSERT INTO Manuscript VALUES ('483','Bible (Genesis-IV Kings)',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('Italy','','483');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','483');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','483');
INSERT INTO Date(Century,Super, MS_Number)VALUES(15,'','483');
INSERT INTO Manuscript VALUES ('486','Ecclesiasticus in Greek',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','486');
INSERT INTO Language (Language, MS_Number) VALUES ('Greek','486');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','486');
INSERT INTO Manuscript VALUES ('422','The Red Book of Darley',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South West England','Uncertain (Sherborne, Dorset)','422');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','422');
INSERT INTO Language (Language, MS_Number) VALUES ('Old English','422');
INSERT INTO Date(Century,Super, MS_Number)VALUES(10,'','422');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','422');
INSERT INTO Manuscript VALUES ('146','The Samson Pontifical',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','COMPLICATED','146');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','146');
INSERT INTO Language (Language, MS_Number) VALUES ('Greek','146');
INSERT INTO Language (Language, MS_Number) VALUES ('Old English','146');
INSERT INTO Language (Language, MS_Number) VALUES ('English','146');
INSERT INTO Date(Century,Super, MS_Number)VALUES(10,'','146');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','146');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','146');
INSERT INTO Manuscript VALUES ('473','The Winchester Troper',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','Winchester','473');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','473');
INSERT INTO Language (Language, MS_Number) VALUES ('Greek','473');
INSERT INTO Language (Language, MS_Number) VALUES ('Old English','473');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'med','473');
INSERT INTO Manuscript VALUES ('162','Old English Homilies',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','Uncertain (Rochester or Canterbury)','162');
INSERT INTO Language (Language, MS_Number) VALUES ('Old English','162');
INSERT INTO Language (Language, MS_Number) VALUES (' Latin','162');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','162');
INSERT INTO Manuscript VALUES ('303','Old English Homilies',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','303');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','303');
INSERT INTO Language (Language, MS_Number) VALUES ('Old English','303');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','303');
INSERT INTO Manuscript VALUES ('415','The Norman Anonymous',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('France','Uncertain (Rouen)','415');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','415');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','415');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','415');
INSERT INTO Manuscript VALUES ('421','Old English Homilies',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Unclear ','421');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','421');
INSERT INTO Language (Language, MS_Number) VALUES ('Old English','421');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','421');
INSERT INTO Manuscript VALUES ('442','Canon Law Collection',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('Fance','Uncertain (Northern France)','442');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','442');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','442');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','442');
INSERT INTO Manuscript VALUES ('72','Gospel Lectionary',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','Canterbury','72');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','72');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'ex','72');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'in','72');
INSERT INTO Manuscript VALUES ('231','Terence, Comedies',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','231');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','231');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'in','231');
INSERT INTO Manuscript VALUES ('393','Historia Eliensis',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('East of England','Ely Pirory','393');
INSERT INTO Language (Language, MS_Number) VALUES ('Lain','393');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','393');
INSERT INTO Manuscript VALUES ('383','Anglo-Saxon Laws',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('London','Uncertain (St. Paul''s Cathedral, London)','383');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','383');
INSERT INTO Language (Language, MS_Number) VALUES ('Old English','383');
INSERT INTO Language (Language, MS_Number) VALUES ('Anglo-Norman','383');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','383');
INSERT INTO Date(Century,Super, MS_Number)VALUES(16,'','383');
INSERT INTO Manuscript VALUES ('478','Armenian Psalter',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','478');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','478');
INSERT INTO Language (Language, MS_Number) VALUES ('Armenian','478');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','478');
INSERT INTO Manuscript VALUES ('42','Lives of Saints',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','Dover Priory ','42');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','42');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','42');
INSERT INTO Manuscript VALUES ('161','Lives of Saints',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','Canterbury','161');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','161');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'ex','161');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'in','161');
INSERT INTO Manuscript VALUES ('628','Psalter (Latin)',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('France','Uncertain (Paris)','628');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','628');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'med','628');
INSERT INTO Manuscript VALUES ('2I','The Bury Bible',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('East of England','Uncertain (Bury St. Edmonds Abbey)','2I');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','2I');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','2I');
INSERT INTO Manuscript VALUES ('2II','The Bury Bible',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('East of England','Uncertain (Bury St. Edmonds Abbey)','2II');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','2II');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','2II');
INSERT INTO Manuscript VALUES ('2III','The Bury Bible',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('East of England','Uncertain (Bury St. Edmonds Abbey)','2III');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','2III');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','2III');
INSERT INTO Manuscript VALUES ('466','Medical Tracts',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','St Augustine''s, Canterbury','466');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','466');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'','466');
INSERT INTO Manuscript VALUES ('190','Penitential',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South West England','Exeter','190');
INSERT INTO Language (Language, MS_Number) VALUES ('Old English','190');
INSERT INTO Language (Language, MS_Number) VALUES (' Latin','190');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','190');
INSERT INTO Manuscript VALUES ('44','Pontifical',1);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','Uncertain (St. Augustine''s, Canterbury) ','44');
INSERT INTO Language (Language, MS_Number) VALUES ('Old English','44');
INSERT INTO Language (Language, MS_Number) VALUES (' Latin','44');
INSERT INTO Date(Century,Super, MS_Number)VALUES(11,'','44');
INSERT INTO Date(Century,Super, MS_Number)VALUES(16,'','44');
INSERT INTO Manuscript VALUES ('48','Bible',3);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain ','48');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','48');
INSERT INTO Date(Century,Super, MS_Number)VALUES(12,'ex','48');
INSERT INTO Manuscript VALUES ('49','Bible',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('South East England','St. Augustine''s, Canterbury ','49');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','49');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','49');
INSERT INTO Manuscript VALUES ('246','Bible',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','246');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','246');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','246');
INSERT INTO Manuscript VALUES ('437','Bible',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('Fance','Uncertain (Northern France)','437');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','437');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','437');
INSERT INTO Manuscript VALUES ('463','Bible',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','463');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','463');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'ex','463');
INSERT INTO Manuscript VALUES ('484','Bible',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','484');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','484');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','484');
INSERT INTO Manuscript VALUES ('485','Bible',2);
INSERT INTO Location (Region, Institution, MS_Number) VALUES('','Uncertain','485');
INSERT INTO Language (Language, MS_Number) VALUES ('Latin','485');
INSERT INTO Date(Century,Super, MS_Number)VALUES(13,'','485');
